defaults:
  - model: test_k50d15n30bk_inf_nucleus_local
  - override hydra/job_logging: 'disabled'

model:
  enabled: True  

cuda_visible_devices: [3]


# Command line arguments
# nohup python3 src/proof_search/tatic_search/provers/proof_search_experiments.py model=test_k50d15n30bk_inf_nucleus_local cuda_visible_devices=[0] &