name: simple_benchmark_1
num_files: 1
datasets:
  - project: data/test/coq/custom_group_theory/theories
    files:
      - path: grpthm.v
        theorems:
          - algb_identity_sum
          - algb_add_comm
          - algb_has_identity
          - associativity
          - algb_has_inverse
          - algb_is_closed
          - algb_is_abelian_group
          - algb_mul_is_closed
          - algb_mul_comm
          - algb_mul_assoc
          - algb_mul_add_distr